# Basic SNMP configuration
agentAddress udp:161
rocommunity public

# System info
sysLocation    Tata Steel Internship Lab
sysContact     Arnav <arnav@example.com>
sysName        virtual-switch-01

# Dynamic metrics using shell scripts
extend cpu /usr/local/bin/cpu.sh
extend memory /usr/local/bin/memory.sh
extend temperature /usr/local/bin/temperature.sh
extend bandwidth /usr/local/bin/bandwidth.sh