# Generated by Django 6.0.5 on 2026-05-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SwitchMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("cpu_usage", models.IntegerField()),
                ("memory_usage", models.IntegerField()),
                ("temperature", models.IntegerField()),
                ("bandwidth", models.IntegerField()),
                ("interface_status", models.IntegerField()),
                ("crc_errors", models.IntegerField()),
                ("reliability", models.CharField(max_length=10)),
                ("tx_rate", models.IntegerField()),
                ("rx_rate", models.IntegerField()),
                ("anomalies", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
