# Generated by Django 6.0.5 on 2026-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_switch_switchmetric_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="switch",
            name="community_string",
            field=models.CharField(default="public", max_length=100),
        ),
        migrations.AddField(
            model_name="switch",
            name="is_demo",
            field=models.BooleanField(default=True),
        ),
    ]
