# Generated by Django 6.0.5 on 2026-05-31 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_switch_community_string_switch_is_demo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("anomaly_type", models.CharField(max_length=200)),
                ("cpu_usage", models.IntegerField()),
                ("temperature", models.IntegerField()),
                ("email_sent", models.BooleanField(default=False)),
                (
                    "switch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="monitor.switch"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
